openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/shortened_urls":
    post:
      summary: create shortened url
      tags:
      - ShortenedUrls
      security:
        - ApiKeyAuth: []  # Reference to the security scheme
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shortened_url:
                  type: object
                  properties:
                    long_url:
                      type: string
                      example: ""
                      description: "The URL to be shortened (e.g., https://example.com)"
                  required:
                  - long_url
              required:
              - shortened_url
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization  # The header name that is required
